name: Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          npm run lint:js
          npm run lint:css

      - name: Run testing
        run: npm run test:run
